title: vx-utku
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Utku Çorbacı
avatar: /logo.png
email: corbaciutku@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: rhotav
  card: summary
logo: logo.png
social:
  name: Utku Çorbacı
  links:
    - https://twitter.com/rhotav
    - https://www.linkedin.com/in/utku-corbaci/
    - https://github.com/polynomen
google_site_verification: 
lang: en
