title: vx.zone
description: vx.zone malware analysis & reverse engineering team
author: vx.zone
avatar: /logo.png
email: 

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: vx-zone

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

skin: midnight
usemathjax: true
# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: malwation
  card: summary
logo: logo.png
social:
  name: vx.zone
  links:
    - https://twitter.com/malwation

google_site_verification: 
lang: en
